version: '3'
services:
  database:
    container_name: postgres_database
    image: postgres:alpine
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres